/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'fsalbaro' at '9/12/14 2:01 PM' with Gradle 2.1
 *
 * @author fsalbaro, @date 9/12/14 2:01 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
