/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'fsalbaro' at '9/12/14 2:01 PM' with Gradle 2.1
 *
 * @author fsalbaro, @date 9/12/14 2:01 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
